name: picosnitch
summary: picosnitch
description: |
  Monitors your bandwidth, breaking down traffic by executable,
  hash, parent, domain, port, or user over time.
confinement: classic
grade: stable
base: core22
version: '0.14.1'

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  picosnitch:
    plugin: python
    source: https://github.com/elesiuta/picosnitch.git
    source-tag: 'v${SNAPCRAFT_PROJECT_VERSION}'
    python-packages:
      - wheel
      - psutil
      - requests
      - pandas
      - plotly
      - dash
      - dash-bootstrap-components
      - dash-bootstrap-templates
      - geoip2
      - psycopg
      - pymysql
    stage-packages:
      - python3-dbus
      - libdebuginfod-dev
    after:
      - bcc

  bcc:
    plugin: cmake
    cmake-parameters:
      - '-DCMAKE_INSTALL_PREFIX=/usr'
      - '-DPYTHON_CMD=/usr/bin/python3'
      - '-DCMAKE_VERBOSE_MAKEFILE=ON'
    source: https://github.com/iovisor/bcc/releases/download/v0.28.0/bcc-src-with-submodule.tar.gz
    build-packages:
      - bison
      - build-essential
      - flex
      - git
      - libclang-14-dev
      - libdebuginfod-dev
      - libedit-dev
      - libelf-dev
      - libllvm14
      - liblzma-dev
      - libfl-dev
      - llvm-14-dev
      - zip
      - zlib1g-dev
      - python3
      - python3-packaging
      - python3-pip
      - python3-setuptools
    prime:
      - usr/bin*
      - usr/lib*

environment:
  PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10/dist-packages

apps:
  picosnitch:
    command: bin/picosnitch

  daemon:
    command: "bin/picosnitch start-no-daemon"
    daemon: simple
    restart-condition: always
    restart-delay: 5s
